### PR TITLE
docs: Updates Readme

### PR DESCRIPTION
**Pull request by chicken-biryani**
- Comments out the installation part. I will add it in a separate document.
- Comments out the supporters part
- Updates Readme

### CODE REVIEW

**Comment by chicken-biryani** [comment]
I tried cloning and pushing directly. But it says "Don't have permission to push. Fork instead" (Something along those lines.)

**Comment by chicken-biryani** [comment]
Update: I checked the checks... And I need to follow the 'conventional commit' method. For the check to pass.

**Comment by jravenel** [comment]
Hi @chicken-biryani, it seems that you did not use one of the below prefix in your commit.
You can look at github action error and it gives you more details on what to put, in our case: "docs: ....."
Screenshot 2022-07-10 at 16 35 29

**Comment by jravenel** [comment]
@chicken-biryani just added "docs: " to name of your PR 🤙

Screenshot 2022-07-10 at 16 46 25

**Comment by jravenel** [comment]
Can we add back the badges @chicken-biryani as discussed in Slack?

**Comment by chicken-biryani** [comment]
Yes. Will add ot in the next PR.

**Pull request merged**
